safety_margin: 1.2

transactions:
  - type: READ
    cpu: 20 #in ms
    ram: 1000 #in kB
    disc: 1 #in kB
  - type: WRITE
    cpu: 40
    ram: 40
    disc: 500
  - type: COMPUTE
    cpu: 100
    ram: 50
    disc: 400