safety_margin: 1.2

transactions:
  - type: READ
    cpu: 20 #CPU time in ms per transaction
    ram: 1000 #kB per core
    disc: 1 #in kB per transaction
  - type: WRITE
    cpu: 40
    ram: 4000
    disc: 500
  - type: COMPUTE
    cpu: 100
    ram: 7000
    disc: 400